# -*- coding: utf-8 -*-
# vim: filetype=python
#
# This source file is subject to the MIT License
# that is bundled with this package in the file LICENSE.txt.
# It is also available through the Internet at this address:
# https://opensource.org/license/mit
#
# @author	Sebastien LEGRAND
# @license	MIT License
#
# @brief	Token dataclass

#----- imports
from dataclasses import dataclass

from .token_type import TokenType


#----- class
@dataclass
class Token:
    """Simple class to represent a token generated by the lexer

    Members:
    - type (TokenType): the type of the token as defined in TokenTypes class
    - value (str): the value of the token as seen in the assembly file
    - row (int): the line where the token appears
    - col (int): the position in the line where the token appears
    """
    type: TokenType = TokenType.UNKNOWN
    value: str = ""
    row: int = 0
    col: int = 0

    def __repr__(self) -> str:
        return f"{self.type.name};{self.row};{self.col};{self.value}"
