# -*- coding: utf-8 -*-
# vim: filetype=python
#
# This source file is subject to the MIT License
# that is bundled with this package in the file LICENSE.txt.
# It is also available through the Internet at this address:
# https://opensource.org/license/mit
#
# @author	Sebastien LEGRAND
# @license	MIT License
#
# @brief	Compiler token class

# ----- imports
from __future__ import annotations
from typing import Any, Dict, List, Optional

from dataclasses import dataclass

from packages.specs import TokenType


#----- classes
@dataclass
class Token:
    """Simple class to represent a token generated by the lexer

    Members:
        type  : the type of the token as defined in TokenTypes class
        value : the value of the token as seen in the assembly file
        row   : the line where the token appears
        col   : the position in the line where the token appears
    """
    type: TokenType = TokenType.UNKNOWN
    value: str = ""
    row: int = 0
    col: int = 0

    def __repr__(self) -> str:
        #return f"{self.type.name:>12} | ({self.row:3},{self.col:3}) | {self.value:10}"
        return f"{self.type.name};{self.row};{self.col};{self.value}"


class TokenStream:
    """Class to hold a stream of tokens"""
    def __init__(self, tokens: List[Token]) -> None:
        """Constructor"""
        self.tokens = tokens
        self.pos = 0

    def peek(self, inc: int = 0) -> Optional[Token]:
        """Return the next token, without consuming it"""
        idx = self.pos + inc
        if idx >= len(self.tokens):
            return None
        if idx < 0:
            return None
        return self.tokens[idx]

    def advance(self) -> Optional[Token]:
        """Return and consume the current token. None if EOF"""
        token = self.peek()
        if token is None:
            return None
        self.pos += 1
        return token

    def expect(self, kind: TokenType) -> bool:
        """Return True if the token has type 'kind'"""
        token = self.peek()
        return (token is not None and token.type == kind)

    def at_end(self) -> bool:
        """True if we have process all the tokens or reached EOF"""
        token = self.peek()
        if token is None:
            return True
        elif token.type == TokenType.EOF:
            return True
        else:
            return False
