# -*- coding: utf-8 -*-
# vim: filetype=python
#
# This source file is subject to the MIT License
# that is bundled with this package in the file LICENSE.txt.
# It is also available through the Internet at this address:
# https://opensource.org/license/mit
#
# @author	Sebastien LEGRAND
# @license	MIT License
#
# @brief	Compiler token class

# ----- imports
from __future__ import annotations
from typing import Any, Dict, List

from dataclasses import dataclass

from packages.specs import TokenType


#----- class
@dataclass
class Token:
    """Simple class to represent a token generated by the lexer

    Members:
        type  : the type of the token as defined in TokenTypes class
        value : the value of the token as seen in the assembly file
        row   : the line where the token appears
        col   : the position in the line where the token appears
    """
    type: TokenType = TokenType.UNKNOWN
    value: str = ""
    row: int = 0
    col: int = 0

    def __repr__(self) -> str:
        return f"{self.type.name:>12} | ({self.row:3},{self.col:3}) | {self.value:10}"
